name: Lint

on: [push]

jobs:
  once:
    runs-on: ubuntu-latest
    - uses: actions/checkout@v1
    - name: Set up Python 3.7
      uses: actions/setup-python@v1
      with:
        python-version: 3.7
    - name: Lint
      run: |
        pip install pre-commit
        pre-commit install-hooks
        pre-commit run --all-files
